name: Build and Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        env:
          NODE_ENV: production
        run: npm run build

      - name: Move dist to build
        run: |
          rm -rf build
          mv dist build

      - name: Commit build folder
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add build
          git commit -m "Update build folder [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
